version: '2'
services:
  sonarr:
    image: linuxserver/sonarr
    container_name: sonarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=UTC
      - UMASK_SET=022 #optional
    volumes:
      - ${BASE_DIR}/volumes/sonarr/data:/config
      - ${BASE_DIR}/media/tvshows:/tv
      - ${BASE_DIR}/downloads:/downloads
    ports:
      - 8989:8989
    restart: unless-stopped

  transmission:
    image: linuxserver/transmission
    container_name: transmission
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=UTC
      - TRANSMISSION_WEB_HOME=/combustion-release/ #optional
#      - USER=username #optional
#      - PASS=password #optional
    volumes:
      - ${BASE_DIR}/volumes/transmission/config:/config
      - ${BASE_DIR}/downloads:/downloads
      - ${BASE_DIR}/downloads/TransmissionWatchFolder:/watch
    ports:
      - 9091:9091
      - 51413:51413
      - 51413:51413/udp
    restart: unless-stopped
  emby:
    image: 'emby/embyserver_arm32v7:latest'
    container_name: emby
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=UTC
    volumes:
      - ${BASE_DIR}/volumes/emby/config:/config
      - ${BASE_DIR}/media:/mnt/share1
    ports:
      - 8096:8096
      - 8920:8920
      - 1900:1900/udp
    restart: unless-stopped